required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: -0.5
  y: 116
  z: 35.5
  yaw: -90
  pitch: 0
arena:
  world: 'world'
  x1: -0.5
  y1: 48
  z1: 1.5
  yaw1: 0
  pitch1: 0
  x2: 33.5
  y2: 48
  z2: 35.5
  yaw2: 90
  pitch2: 0
  x3: -0.5
  y3: 48
  z3: 69.5
  yaw3: -180
  pitch3: 0
  x4: -34.5
  y4: 48
  z4: 35.5
  yaw4: -90
  pitch4: 0